backend:
  name: github
  repo: alisardari3696/alisardari3696.github.io
  branch: main

site_url: https://alisardari3696.netlify.app

media_folder: "images/uploads"      # Folder inside repo for uploaded images
public_folder: "/images/uploads"    # Public path for images

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "body", label: "Body", widget: "markdown" }
